env:
# ENCRYPTED
  RCLONECONFIG_DRIVE: "ENCRYPTED[e5639a37e8afbda65b3a20066cbc54a05b5161b7ef88fe4327c7ca9711d9f1a9263081eb600861c1e038ba3a648af919]"
  TG_TOKEN: "ENCRYPTED[1aa8a68e8d24caa162af90768f8e73423eef7314ef7b7daaf21987169a583ec58bbfa95d90613569eae110fdd0036ac8]"
  TG_CHAT_ID: "ENCRYPTED[758f05e53b09983db8a8ca80e2a9c9f01d2f54086001a9261f13f7340235a576e422ba8bf1ddaab96924749fd031157c]"
  CREDENTIALS: "ENCRYPTED[0c7f59502bc66606e83696f0908d8c80eeab692bb7bfb95e6910d57bc473490d73eef06e0770ae0c8b9c6a11b219e821]"
  EMAIL: "ENCRYPTED[c5b824f3abe58ff89279d82aaaaa8ed5e3538ad7b12a6e1fdc1dbf3ec0412b79484b8b7c6dbe0a531f90e8328815ca5a]"

# FLAG
  WORKDIR: "/tmp"
  CIRRUS_CLONE_DEPTH: "1"

task:
  name: "Setting Up, Syncing, Building and Uploading"
  only_if: $CIRRUS_REPO_OWNER == 'IQ-7'
  timeout_in: 120m
  container:
    image: chalkzone/build:22.04
    cpu: 8
    memory: 32G

  Memuat-ccache_background_script:
     - ./script/memuat_ccache.sh
     
  Repo-pribadi_script:
     - git config --global user.name "IQ-7"
     - git config --global user.email "$EMAIL"
     - echo "$CREDENTIALS" > ~/.git-credentials
     - git config --global credential.helper store --file=~/.git-credentials

  Sinkronisasi_script:
     - ./script/sinkronisasi.sh
     
  Build-rom_script:
     - ./script/membangun.sh
     
  Ccache-info_script:
     - set -e
     - export CCACHE_DIR=$WORKDIR/ccache
     - ccache -s
     
  Upload-build_script:
     - ./script/mengemas.sh
     
