env:
# ENCRYPTED
  RCLONECONFIG_DRIVE: "ENCRYPTED[5da697c2bd92fe743dce6942204e64e116873e645cb1d91209ae8bc37cc111677c86d04c51f6bf23fce340b1fd880fb6]
  TG_TOKEN: "ENCRYPTED[91bc34b9e709c62edcd8b693026997e4467fa4385f39da58773ead45c56604dc58410471f527756d09ce3d9a34da2d6c]"
  TG_CHAT_ID: "ENCRYPTED[ed4c6c7241ab9bc353f1814272c31dd4b838200c778157d935286e3ea043e53a523e84d61ee2dfd3152fccc88014f75d]"
  EMAIL: "ENCRYPTED[627d38fdf9c3b5c5e01624252de0044129984045b856aa95bad66dc43076113a0d60d04f5bb7af7f02b30a73d529f85e]"

# FLAG
  WORKDIR: "/tmp"
  CIRRUS_CLONE_DEPTH: "1"

task:
  name: "Setting Up, Syncing, Building and Uploading"
  timeout_in: 120m
  container:
    image: chalkzone/build:22.04
    cpu: 8
    memory: 32G

  Memuat-ccache_background_script:
     - ./script/memuat_ccache.sh
     
  Repo-pribadi_script:
     - git config --global user.name "parikk"
     - git config --global user.email "$EMAIL"

  Sinkronisasi_script:
     - ./script/sinkronisasi.sh
     
  Build-rom_script:
     - ./script/membangun.sh
     
  Ccache-info_script:
     - set -e
     - export CCACHE_DIR=$WORKDIR/ccache
     - ccache -s
     
  Upload-build_script:
     - ./script/mengemas.sh
     
